### ISSUE TITLE
how to import this to sails js ? 

### ISSUE THREAD

**Issue by edades** [Acquisio/bootstrap-stylus#87]
Hi, i try to import this to my project in sails js.
I don't know where put this code: 

var bootstrap = require('bootstrap-styl'),
    stylus    = require('stylus');

function compile(str) {
  return stylus(str)
    .use(bootstrap());
}

i have this: 
![captura de pantalla 2015-01-12 a las 17 53 37](https://cloud.githubusercontent.com/assets/401513/5710813/fb8f210e-9a83-11e4-98fd-7452cc76b1e3.png)

thanks.

**Comment by morenoh149** [comment]
@edades ask the sailsjs guys. Not here. BTW check out http://keystonejs.com/ for something similar to sails.
